language: python
python:
  - "2.7"
before_script: sudo apt-get install python-numpy python-pyside python-matplotlib python-h5py && export PYTHONPATH=$PYTHONPATH:~/taskontrol

#command to install dependencies
# command to run tests
script: nosetests
